### ISSUE TITLE
Add Documentation to the website

### ISSUE THREAD

**Issue by nikhilmufc7** [nikhilmufc7/Restaurant.github.io#1]
This website was created as part of the final project of the coursera web development course by John hopkins university. I would be glad if someone can add a documentation explaining this and the features a bit. Good first issue if you want to make a pull request as part of Hacktoberfest

**Comment by sanghisha145** [comment]
Hi, do you want each element in restaurant webpage to be explained or general overview and features involved?

**Comment by nikhilmufc7** [comment]
Just general overview. Even 5 lines would do

**Comment by AugustasV** [comment]
Only for me link not working?

**Comment by AugustasV** [comment]
Ok i will do that
